# Generated by Django 2.2.15 on 2020-09-19 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emojiapp', '0002_auto_20200919_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mealName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MealTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mealTimeName', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='testentry',
            name='beforeAfter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emojiapp.MealTime'),
        ),
        migrations.AlterField(
            model_name='testentry',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emojiapp.Meal'),
        ),
    ]
